### ISSUE TITLE
地图编辑器瓷砖可选数量目前最多只有16个

### ISSUE THREAD

**Issue by SuCicada** [SuCicada/Algorithm-PlayGround#1]
因为用的是texture 生成图形的方式(详情:https://photonstorm.github.io/phaser-ce/Phaser.Create.html#texture)
它只支持0-F的字符(即色块),即便换了调色板(即色块颜色组), 也最多十六种.
这样会不会可能不够用, 这是一个问题.

**Comment by SuCicada** [comment]
> 因为用的是texture 生成图形的方式(详情:https://photonstorm.github.io/phaser-ce/Phaser.Create.html#texture)
> 它只支持0-F的字符(即色块),即便换了调色板(即色块颜色组), 也最多十六种.
> 这样会不会可能不够用, 这是一个问题.

可不可以只是说: 这只是简易版, 更多功能使用tiled 或期待后续版本
(之后可以加入导入本地贴图集, 并且支持贴图裁剪,自动拼接,以满足界面需求)

**Comment by llwwdbd** [comment]
Tiled can be downloaded  form this website.
可以从这网站中下载Tiled。
https://www.mapeditor.org/
